spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eggcoach
    username: eggcoach
    password: eggcoach1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true